apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oidc-keycloak-bff

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - keycloak-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml

